%
% License:  This  program  is  free software; you can redistribute it and/or
% modify  it  under the terms of the GNU General Public License as published
% by  the  Free Software Foundation; either version 3 of the License, or (at
% your  option)  any  later version. This program is distributed in the hope
% that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
% warranty  of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
% GNU General Public License for more details.
%

function fig = BodyMechControlWindow()
% BODYMECHCONTROLWINDOW [ BodyMech 3.06.01 ]: creates main user i/o window
% INPUT
%       Input : none
% PROCESS
%       creates main BodyMech Graphical User Interface features
% OUTPUT
%       BodyMech GUI

% AUTHOR(S) AND VERSION-HISTORY
% $ Ver 1.0 Creation (Jaap Harlaar, VUmc, Amsterdam, December 2003)
% $ Ver 3.06.01 VUmc, Amsterdam, May 2006 (Jaap Harlaar en Caroline Doorenbosch) 

% Copyright 2000-2006 This program is free software under the terms of the GNU General Public License (www.gnu.org) declaration
BodyMechFuncHeader

load BodyMechMainFigure

%  ==================================
%  Figure Size
%  ==================================
BMCW_height= 650; % 550
BMCW_width= 535;  % 485
InternalBorder=5;

scrsz = get(0,'ScreenSize');
scr_width=scrsz(3);
scr_heigth=scrsz(4);

BMCW_size=[BMCW_width BMCW_height];

menu_area=40; % window's title bar(20), menu bar(20), (no toolbar)

BMCW_origin=[20  scr_heigth-BMCW_height-menu_area];

h0 = figure('Color',[0.8 0.8 0.8], ...
    'Colormap',mat0, ...
    'FileName','C:\temp\BodyMechLatestControlWindow.m', ...
    'Name','BodyMech BODY', ...
    'NumberTitle','off', ...
    'PaperPosition',[18 180 576 432], ...
    'PaperType','A4', ...
    'PaperUnits','points', ...
    'Position',[BMCW_origin BMCW_size], ...
    'Resize','Off',...
    'RendererMode','manual', ...
    'Tag','BodyMechControlWindow', ...
    'DefaultAxesFontSize',10,...
    'MenuBar','none',...
    'ToolBar','none');


%  ==================================
%  Logo
%  ==================================


LogoSize=[110 110];
LogoOriginX=2*InternalBorder;
LogoOriginY=BMCW_height-LogoSize(2)-2*InternalBorder;
LogoOrigin=[LogoOriginX LogoOriginY];

h1 = axes('Parent',h0, ...
	'Units','pixels', ...
	'Box','on', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color',[1 1 1], ...
	'ColorOrder',mat1, ...
	'Layer','top', ...
	'Position',[LogoOrigin LogoSize], ...
	'Tag','Axes1', ...
	'TickDirMode','manual', ...
	'Visible','off', ...
	'XColor',[0 0 0], ...
	'XLim',[0.5 300.5], ...
	'XLimMode','manual', ...
	'YColor',[0 0 0], ...
	'YDir','reverse', ...
	'YLim',[0.5 300.5], ...
	'YLimMode','manual', ...
	'ZColor',[0 0 0]);
h2 = image('Parent',h1, ...
	'CData',mat2, ...
	'Tag','BMCW_Logo', ...
	'XData',[1 300], ...
   'YData',[1 300]);

%  ==================================
%  BODYMECH MODEL info window
%  ==================================

BMMinfoWindowTitleSize=[200 20];
BMMinfoWindowSize=[BMCW_width-LogoSize(1)-5*InternalBorder   BMCW_height-2*InternalBorder-BMMinfoWindowTitleSize(2)];
BMMinfoWindowOrigin=[BMCW_width-InternalBorder-BMMinfoWindowSize(1) InternalBorder];
BMMinfoWindowTitleOrigin=[BMMinfoWindowOrigin(1)+0.5*BMMinfoWindowSize(1)-0.5*BMMinfoWindowTitleSize(1) BMMinfoWindowOrigin(2)+BMMinfoWindowSize(2)+InternalBorder];

h1 = uicontrol('Parent',h0, ...
    'Units','pixels', ...
    'BackgroundColor',[.9 .9 .9],...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[BMMinfoWindowOrigin BMMinfoWindowSize], ...
    'String','NO BODY MODEL ACTIVE', ...
    'Style','listbox', ...
    'ListboxTop',1, ...
    'Callback','BodyMechMenuFcn(''list_body_model'')', ...
    'Tag','BodyMechModelInfoWindow');

h1 = uicontrol('Parent',h0, ...
   'Style','Text',...
   'String','BODY MODEL INFO',...
   'Position',[BMMinfoWindowTitleOrigin  BMMinfoWindowTitleSize],...
   'ForegroundColor',[0 0 0.6],...
   'BackgroundColor',[0.8 0.8 0.8],...
   'FontSize',10,...   
   'FontWeight','Bold');

%  ==================================
%  BUTTONS
%  ==================================

Button_Size=[110 30];

Button1_Origin=[2*InternalBorder LogoOriginY-Button_Size(2)-2*InternalBorder]; 

h1 = uicontrol('Parent',h0, ...
	'Units','pixels', ...
	'BackgroundColor',[0.75 0.75 0.75], ...
	'Callback','BodyMechMenuFcn(''list_body_model'')', ...
	'ListboxTop',0, ...
	'Position',[Button1_Origin Button_Size], ...
	'String','Update Info', ...
   'Tag','BMCWB_ListBodyModel');

Button2_Origin=[2*InternalBorder Button1_Origin(2)-Button_Size(2)-2*InternalBorder]; 

h1 = uicontrol('Parent',h0, ...
	'Units','pixels', ...
	'BackgroundColor',[0.75 0.75 0.75], ...
	'Callback','BodyMechMenuFcn(''load_bmb'')', ...
	'ListboxTop',0, ...
	'Position',[Button2_Origin Button_Size], ...
	'String','Load BMB file', ...
   'Tag','BMCWB_LoadBMBfile');

Button3_Origin=[2*InternalBorder Button2_Origin(2)-Button_Size(2)-2*InternalBorder]; 

h1 = uicontrol('Parent',h0, ...
	'Units','pixels', ...
	'BackgroundColor',[0.75 0.75 0.75], ...
	'Callback','BodyMechMenuFcn(''kinematic_window'')', ...
    'ListboxTop',0, ...
	'Position',[Button3_Origin Button_Size], ...
	'String','Kinematic Display', ...
   'Tag','BMCWB_KinematicWindow');

Button4_Origin=[2*InternalBorder Button3_Origin(2)-Button_Size(2)-2*InternalBorder]; 

%  ==================================
%  MENU
%  ==================================
 
% ################## 
% ## menu PROJECT ##
% ##################  
  
h1 = uimenu('Parent',h0, ...
	'Label','&Project', ...
   'Tag','BMCWM_Project');
h2 = uimenu('Parent',h1, ...
	'Callback','BodyMechMenuFcn(''load_project_file'')', ...
	'Label','&Load Project file (*.bmb)', ...
	'Tag','BMCWM_Project_LoadProjectFile');
h2 = uimenu('Parent',h1, ...
   'Callback','BodyMechMenuFcn(''update_projectheader'')', ...
   'Label','&Update ProjectHeader', ...
   'Separator','off', ...
   'Tag','BMCWM_Project_UpdateProjectheader');
h2 = uimenu('Parent',h1, ...
	'Callback','BodyMechMenuFcn(''clear_all'')', ...
     'Separator','off', ...
	'Label','&Clear All', ...
	'Tag','BMCWM_Project_ClearBody');

h2 = uimenu('Parent',h1, ...
	'Label','&Start Project', ...
     'Separator','on', ...
	'Tag','BMCWM_Project_StartProjectmodel');
    
    h3 = uimenu('Parent',h2, ...
        'Callback','BodyMechMenuFcn(''run_projectmodel'')', ...
        'Label','&Run ProjectModel', ...
        'Tag','BMCWM_Project_RunProjectmodel');
    h3 = uimenu('Parent',h2, ...
        'Callback','BodyMechMenuFcn(''edit_newprojectmodel'')', ...
        'Label','&Edit ProjectModel (from template)', ...
        'Tag','BMCWM_Project_EditProjectmodel');
 
    h3 = uimenu('Parent',h2, ...
        'Callback','BodyMechMenuFcn(''edit_newanatcalcfunction'')', ...
        'Label','&Edit Anatomical CalculationFunction (from template)', ...
        'Tag','BMCWM_Project_EditAnatCalc');

h2 = uimenu('Parent',h1, ...
	'Callback','BodyMechMenuFcn(''save_projectmodel'')', ...
	'Label','&Save Project file (*.bmb)', ...
     'Separator','on', ...
	'Tag','BMCWM_Project_SaveProjectmodel');

% ################## 
% ## menu SESSION ##
% ################## 

h1 = uimenu('Parent',h0, ...
	'Label','&Session', ...
	'Tag','BMCWM_Session');
h2 = uimenu('Parent',h1, ...
	'Callback','BodyMechMenuFcn(''load_session_file'')', ...
	'Label','&Load Session file (*.bmb)', ...
	'Tag','BMCWM_Session_LoadSessionFile');
h2 = uimenu('Parent',h1, ...
    'Callback','BodyMechMenuFcn(''update_sessionheader'')', ...
    'Label','&Define SessionHeader', ...
    'Tag','BMCWM_Session_UpdateSessionheader');
h2 = uimenu('Parent',h1, ...
	'Callback','BodyMechMenuFcn(''clear_session'')', ...
	'Label','&Clear Session', ...
	'Tag','BMCWM_Session_ClearSession');
h2 = uimenu('Parent',h1, ...
    'Callback','BodyMechMenuFcn(''import_static_trial'')', ...
    'Separator','on', ...  
    'Label','&Import Static Trial (OptoTrak file)', ...
    'Tag','BMCWM_Session_ImportStaticTrial');

h2 = uimenu('Parent',h1, ...
    'Callback','BodyMechMenuFcn(''define_markerclusters'')', ...
    'Label','Define &MarkerClusters', ...
    'Tag','BMCWM_Session_DefineMarkerclusters');
h2 = uimenu('Parent',h1, ...
    'Callback','BodyMechMenuFcn(''define_referenceposture'')', ...
    'Label','Define &ReferencePosture', ...
    'Tag','BMCWM_Session_DefineReferenceposture');
h2 = uimenu('Parent',h1, ...
    'Callback','BodyMechMenuFcn(''define_anatomical_marks'')', ...
     'Separator','on', ...
    'Label','Define &Anatomical Markers', ...
    'Tag','BMCWM_Session_DefineAnatomicalMarks');

h2 = uimenu('Parent',h1, ...
    'Callback','BodyMechMenuFcn(''save_sessionmodel'')', ...
    'Label','Save Session file (*.bmb)', ...
    'Separator','on', ...
    'Tag','BMCWM_Session_SaveSessionmodel');

    % ################
    % ## menu TRIAL ##
    % ################

    h1 = uimenu('Parent',h0, ...
        'Label','&Trial', ...
        'Tag','BMCWM_Trial');
    h2 = uimenu('Parent',h1, ...
        'Callback','BodyMechMenuFcn(''load_trial_file'')', ...
        'Label','&Load Trial file (*.bmb)', ...
        'Tag','BMCWM_Trial_LoadTrialFile');
    h2 = uimenu('Parent',h1, ...
        'Callback','BodyMechMenuFcn(''update_trialheader'')', ...
        'Label','&Define TrialHeader', ...
        'Tag','BMCWM_Trial_UpdateTrialheader');
    h2 = uimenu('Parent',h1, ...
        'Callback','BodyMechMenuFcn(''clear_trial'')', ...
        'Label','&Clear Trial', ...
        'Tag','BMCWM_Trial_ClearTrial');
    
    h2 = uimenu('Parent',h1, ...
        'Label','Import &Marker file (OptoTrak)', ...
        'Separator','on', ...
        'Callback','BodyMechMenuFcn(''import_NDF'')', ...
        'Tag','BMCWM_Trial_ImportMarkerFile');
    h2 = uimenu('Parent',h1, ...
        'Callback','BodyMechMenuFcn(''import_C3D'')', ...
        'Enable','off', ...
        'Label','Import &C3D', ...
        'Tag','BMCWM_Trial_ImportC3D');
    h2 = uimenu('Parent',h1, ...
        'Label','Import &Analog Data File', ...
        'Tag','BMCWM_Trial_ImportAnalogFile');
    h3 = uimenu('Parent',h2 , ...
        'Callback','BodyMechMenuFcn(''import_MDF'')', ...
        'Label','Import &MDF', ...
        'Tag','BMCWM_Trial_ImportMDF');
    h3 = uimenu('Parent',h2 , ...
        'Enable','on', ...
        'Callback','BodyMechMenuFcn(''import_TMS'')', ...
        'Label','Import &TMS', ...
        'Tag','BMCWM_Trial_ImportTMS');
    h3 = uimenu('Parent',h2, ...
        'Enable','on', ...
        'Callback','BodyMechMenuFcn(''import_DAR'')', ...
        'Label','Import &DAR', ...
        'Tag','BMCWM_Trial_ImportDAR');
     h3 = uimenu('Parent',h2, ...
        'Callback','BodyMechMenuFcn(''import_ASCII'')', ...
        'Enable','off', ...
        'Label','Import &ASCII', ...
        'Tag','BMCWM_Trial_ImportASCII');
    h2 = uimenu('Parent',h1, ...
        'Label','Correct Offset &ForceSignal', ...
        'Callback','BodyMechMenuFcn(''CorrectForceOffset'')', ...
        'Tag','BMCWM_TrialCorrectForceOffset');
	
% make selection of timeinterval
  	h2 = uimenu('Parent',h1, ...
          	'Callback','BodyMechMenuFcn(''selectmarkerkinematics'')', ...
            'Separator','on', ...      
			'Label','Select &TimeInterval Markers', ...
            'Tag','BMCWM_Trial_SelectMarkerKinematics');
 
	h2 = uimenu('Parent',h1, ...
        'Callback','BodyMechMenuFcn(''kinematicscalculation'')', ...
        'Label','&KinematicsCalculation', ...
        'Tag','BMCWM_Trial_Kinematicscalculation');
 
	h2 = uimenu('Parent',h1, ...
        'Label','KinematicsCalculation&Steps', ...
        'Tag','BMCWM_Trial_Kinematicscalculationsteps');
    
         h3 = uimenu('Parent',h2, ...
            'Callback','BodyMechMenuFcn(''interpolatemarkers'')', ...
            'Label','&Interpolate Marker Kinematics', ...
            'Tag','BMCWM_Trial_InterpolateMarkers');
        h3 = uimenu('Parent',h2, ...
            'Callback','BodyMechMenuFcn(''calculate_clusterkinematics'')', ...
            'Label','Calculate &Cluster kinematics', ...
            'Tag','BMCWM_Trial_CalculateClusterKinematics');
        h3 = uimenu('Parent',h2, ...
            'Callback','BodyMechMenuFcn(''kinematics_posture_referenced'')', ...
            'Separator','on', ...
            'Label','Segment kinematics (&Posture referenced)', ...
            'Tag','BMCWM_Trial_KinematicsPostureReferenced');
        h3 = uimenu('Parent',h2, ...
            'Callback','BodyMechMenuFcn(''virtualmarks'')', ...
            'Label','&Virtual markers', ...
            'Tag','BMCWM_Trial_VirtualMarks');
        h3 = uimenu('Parent',h2, ...
            'Callback','BodyMechMenuFcn(''stickfigure'')', ...
            'Label','Create a default &Stick figure', ...
            'Tag','BMCWM_Trial_StickFigure');
        
        h3 = uimenu('Parent',h2, ...
            'Callback','BodyMechMenuFcn(''joint_kinematics_posture_ref'')', ...
            'Separator','on', ...
            'Label','&Joint kinematics (Posture referenced)', ...
            'Tag','BMCWM_Trial_JointKinematicsPosture');

        
h2 = uimenu('Parent',h1, ...
        'Label','KinematicsCalculation (Anatomy Referenced)', ...
        'Separator','off', ...
        'Tag','BMCWM_Trial_KinematicsAnatomy');
    
         h3 = uimenu('Parent',h2, ...
             'Enable','on', ...
             'Callback','BodyMechMenuFcn(''kinematics_anatomy_referenced'')', ...
             'Label','Segment kinematics', ...
             'Tag','BMCWM_Trial_KinematicsAnatomyReferenced');
        h3 = uimenu('Parent',h2, ...
            'Enable','on', ...
            'Callback','BodyMechMenuFcn(''joint_kinematics_anatomy_ref'')', ...
            'Label','&Joint kinematics', ...
            'Tag','BMCWM_Trial_JointKinematicsAnatomy');
    h2 = uimenu('Parent',h1, ...
        'Callback','BodyMechMenuFcn(''save_trialmodel'')', ...
        'Label','Save Trial file (*.bmb)', ...
        'Separator','on', ...
        'Tag','BMCWM_Trial_SaveTrialmodel');
    h2 = uimenu('Parent',h1, ...
        'Enable','off', ...
        'Label','&Export data', ...
        'Tag','BMCWM_Trial_Exportdata');

%  ==================================
% VIEW MENU
%  ==================================

h1 = uimenu('Parent',h0, ...
	'Enable','on', ...
	'Label','&View', ...
   'Tag','BodyMechViewUImenu');

h2 = uimenu('Parent',h1, ...
	'Enable','on', ...
	'Callback','BodyMechMenuFcn(''Orthogonal_display'')', ...
	'Label','Show &Orthogonal Views', ...
	'Tag','&Viewuimenu4');

h2 = uimenu('Parent',h1, ...
	'Enable','on', ...
	'Callback','BodyMechMenuFcn(''GraphMarkers'')', ...
	'Label','graph &Marker', ...
	'Separator','on', ...
	'Tag','&Viewuimenu7');
h2 = uimenu('Parent',h1, ...
	'Enable','on', ...
	'Callback','BodyMechMenuFcn(''graph_joint_kinematics'')', ...
	'Label','graph &Joint angles', ...
   'Tag','&Viewuimenu9');
h2 = uimenu('Parent',h1, ...
	'Enable','on', ...
	'Separator','on', ...
	'Callback','BodyMechMenuFcn(''graph_SRE'')', ...
	'Label','graph &SREMG', ...
   'Tag','&Viewuimenu2');
h2 = uimenu('Parent',h1, ...
	'Enable','on', ...
	'Separator','off', ...
	'Callback','BodyMechMenuFcn(''graph_Raw_EMG'')', ...
	'Label','graph &Raw EMG signal', ...
   'Tag','&Viewuimenu2');
h2 = uimenu('Parent',h1, ...
	'Enable','on', ...
	'Separator','on', ...
	'Callback','BodyMechMenuFcn(''graph_force'')', ...
	'Label','Ext force graphs', ...
   'Tag','&Viewuimenu2');


if nargout > 0, fig = h0; end
% ============================================ 
% END ### BodyMechControlWindow ###
