%
% License:  This  program  is  free software; you can redistribute it and/or
% modify  it  under the terms of the GNU General Public License as published
% by  the  Free Software Foundation; either version 3 of the License, or (at
% your  option)  any  later version. This program is distributed in the hope
% that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
% warranty  of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
% GNU General Public License for more details.
%

function fig = OrthoView(lab_area)
% ORTHOVIEW [ BodyMech 3.06.01 ]: Opens orthogonal display window
% INPUT
%   lab_area: (xlow, xhigh, ylow, yhigh, zlow, zhigh]
% PROCESS
%   Creates window with kinematics menu and orthogonal plane views

% AUTHOR(S) AND VERSION-HISTORY
% $ Ver 1.0 Creation (Jaap Harlaar, VUmc)
% $ Ver 3.06.01 VUmc, Amsterdam, May 2006 (Jaap Harlaar en Caroline Doorenbosch) 

% Copyright 2000-2006 This program is free software under the terms of the
% GNU General Public License (www.gnu.org) 

BodyMechFuncHeader

VIZ.ORTHOMODE=[0 0 0 0 0 0 0]; 

load orthoview

xlow=lab_area(1);
xhigh=lab_area(2); 
ylow=lab_area(3); 
yhigh=lab_area(4);
zlow =lab_area(5);
zhigh=lab_area(6);

scrsz = get(0,'ScreenSize');
scr_width=min(1024,scrsz(3));
scr_heigth=min(768,scrsz(4));

border=30;

%fig_size=[scr_width-2*border scr_heigth-2*border];

fig_origin=[5 35];
fig_size=[860 690];

paper_h=21; paper_w=29; % A4 landscape

pfig_hmax=.7*paper_h; pfig_wmax=.7*paper_w;
h_border=.15*paper_h; w_border=.15*paper_w;
scr_ratio=fig_size(1)/fig_size(2);
paper_ratio=pfig_wmax/pfig_hmax;

if scr_ratio >= paper_ratio;
   pfig_w=pfig_wmax; pfig_h=pfig_w/scr_ratio;
else 
   pfig_h=pfig_hmax; pfig_w=pfig_h*scr_ratio;
end

gf=.6;

% ===========
h0 = figure('Units','pixels', ...
   'Color',[0.8 0.8 0.8], ...
   'Colormap',mat0, ...
   'FileName','C:\temp\orthoview_latest.m', ...
   'Name','Orthogonal plane views', ...
   'NumberTitle','off', ...
   'PaperType','A4',...
   'PaperOrientation','landscape',...
   'PaperUnits','centimeters', ...
   'PaperPosition',[w_border h_border  pfig_w  pfig_h], ...
   'Position',[fig_origin fig_size], ...
   'Resize','on',...  
   'MenuBar','none',...
   'ToolBar','none',... 
   'DefaultUIControlFontSize',8, ...
   'InvertHardCopy','on',...  
   'Tag','OrthoDisplay');

set(h0,'DefaultAxesFontSize',8)

% control area is the upper left corner of the figure
ca_size=[250 250]; %fixed 
ca_origin=[0 fig_size(2)-ca_size(2)];
ca_position=[ca_origin ca_size];

% ===================================
% TIME-SLIDER
% ===================================

slider_size=[180 20];
separation=10;
axis_area=35;
slider_origin=ca_origin+[60 5];
slider_step=[.01 .1];

h1 = uicontrol('Parent',h0, ...
    'Units','pixels', ...
    'BackgroundColor',[0.8 0.8 0.8], ...
    'Callback','UpdateVizTime',...
    'ListboxTop',0, ...
    'Position',[slider_origin slider_size], ...
    'Style','slider', ...
    'SliderStep',slider_step,...
    'Tag','OrthoSlider', ...
    'Value',0.02);

% ====================================
% LOGO
% ====================================
logo_size=[120 120];
logo_origin(1)=ca_origin(1)+separation;
logo_origin(2)=fig_size(2)-separation-logo_size(2);

h1 = axes('Parent',h0, ...
	'Units','pixels', ...
	'Box','on', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color',[1 1 1], ...
	'ColorOrder',mat1, ...
	'Layer','top', ...
   'Position',[logo_origin logo_size], ...
   'Tag','bm_logo', ...
	'XColor',[0 0 0], ...
	'XLim',[0.5 300.5], ...
	'XLimMode','manual', ...
	'XTickMode','manual', ...
	'YColor',[0 0 0], ...
	'YDir','reverse', ...
	'YLim',[0.5 300.5], ...
	'YLimMode','manual', ...
	'YTickMode','manual', ...
   'ZColor',[0 0 0]); 

h2 = image('Parent',h1, ...
	'CData',mat2, ...
	'Tag','Image1', ...
	'XData',[1 300], ...
	'YData',[1 300]);

% ====================================
% ORTHOGONAL VIEW FRAMES
% ====================================

axes_border=30;
title_border=30;
net_size=[fig_size(1)-2*axes_border fig_size(2)-2*axes_border-2*title_border];

xrange=xhigh-xlow;
yrange=yhigh-ylow;
zrange=zhigh-zlow;

crit_meas_a=net_size(1)*(zrange)/(zrange+xrange);
crit_meas_b=net_size(2)*(zrange)/(zrange+yrange);
crit_meas_c=300-axes_border;

crit_meas=min([crit_meas_a crit_meas_b crit_meas_c]);

real2scrn=crit_meas/zrange;

sagit_size=[round(real2scrn*xrange) round(real2scrn*yrange)];
trans_size=[round(real2scrn*xrange) round(real2scrn*zrange)];
front_size=[round(real2scrn*zrange) round(real2scrn*yrange)];

front_orig=[300-front_size(1) axes_border];
sagit_orig=[300+axes_border axes_border];
trans_orig=[300+axes_border 2*axes_border+title_border+sagit_size(2)];

% ====================================
% SAGITTAL VIEW
% ====================================
h1 = axes('Parent',h0, ...
	'Units','pixels', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color',[gf gf gf], ...
	'ColorOrder',mat3, ...
	'DataAspectRatioMode','manual', ...
   'Position',[sagit_orig sagit_size], ...
	'Tag','SideView', ...
	'WarpToFill','off', ...
   'WarpToFillMode','manual', ...
   'NextPlot','replacechildren',...
	'XColor',[0 0 0], ...
	'XLim',[xlow xhigh], ...
	'XLimMode','manual', ...
	'YColor',[0 0 0], ...
	'YLim',[ylow yhigh], ...
	'YLimMode','manual', ...
   'ZColor',[0 0 0]);

title_orig=[sagit_orig(1)+.4*sagit_size(1) sagit_orig(2)+sagit_size(2)+.1*title_border];

h1 = uicontrol('Parent',h0, ...
   'Style','Text',...
   'String','Top View',...
   'Position',[title_orig 100 title_border*.8],...
   'ForegroundColor',[0 0 0.6],...
   'BackgroundColor',[0.8 0.8 0.8],...
   'FontSize',10,...   
   'FontWeight','Bold');

% ====================================
% FRONTAL VIEW
% ====================================
h1 = axes('Parent',h0, ...
	'Units','pixels', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color',[gf gf gf], ...
	'ColorOrder',mat5, ...
	'DataAspectRatioMode','manual', ...
	'Position',[front_orig front_size], ...
   'NextPlot','replacechildren',...
	'Tag','FrontView', ...
	'WarpToFill','off', ...
	'WarpToFillMode','manual', ...
	'XColor',[0 0 0], ...
	'XLim',[zlow zhigh], ...
	'XLimMode','manual', ...
	'YColor',[0 0 0], ...
	'YLim',[ylow yhigh], ...
	'YLimMode','manual', ...
	'ZColor',[0 0 0]);

title_orig=[front_orig(1)+.3*front_size(1) front_orig(2)+front_size(2)+.1*title_border];

h1 = uicontrol('Parent',h0, ...
   'Style','Text',...
   'String','Side2 View',...
   'Position',[title_orig 100 title_border*.8],...
   'ForegroundColor',[0 0 0.6],...
   'BackgroundColor',[0.8 0.8 0.8],...
   'FontSize',10,...   
   'FontWeight','Bold');

% ====================================
% TRANSVERSAL VIEW
% ====================================
h1 = axes('Parent',h0, ...
	'Units','pixels', ...
	'CameraUpVector',[0 1 0], ...
	'Color',[gf gf gf], ...
	'ColorOrder',mat6, ...
	'DataAspectRatioMode','manual', ...
	'Position',[trans_orig trans_size], ...
   'Tag','TopView', ...
   'NextPlot','replacechildren',...
	'WarpToFill','off', ...
	'XColor',[0 0 0], ...
	'XLim',[xlow xhigh], ...
	'XLimMode','manual', ...
	'YColor',[0 0 0], ...
	'YLim',[zlow zhigh], ...
	'YLimMode','manual', ...
	'YDir','reverse', ...
   'ZColor',[0 0 0]);

title_orig=[trans_orig(1)+.4*trans_size(1) trans_orig(2)+trans_size(2)+.1*title_border];

h1 = uicontrol('Parent',h0, ...
   'Style','Text',...
   'String','Side1 View',...
   'Position',[title_orig 100 title_border*.8],...
   'ForegroundColor',[0 0 0.6],...
   'BackgroundColor',[0.8 0.8 0.8],...
   'FontSize',10,...   
   'FontWeight','Bold');

% ====================================
% CHECKBOXES
% ====================================

cb_size=[150 15];
cb_origin=[separation*2+logo_size(1) fig_size(2)-separation-cb_size(2)];
next_cb=-20;

h1 = uicontrol('Parent',h0, ...
   'Units','pixels', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','UpdateVizOrthoMode', ...
   'ListboxTop',0, ...
   'Position',[cb_origin cb_size], ...
   'String','Markers', ...
   'Style','checkbox', ...
   'Enable','on',...
   'Tag','ClusterMarkerCheck', ...
   'UserData','[ ]', ...
   'Value',0);

cb_origin=cb_origin+[0 next_cb];
h1 = uicontrol('Parent',h0, ...
	'Units','pixels', ...
   'Callback','UpdateVizOrthoMode', ...
'BackgroundColor',[0.8 0.8 0.8], ...
  'ListboxTop',0, ...
   'Position',[cb_origin cb_size], ...
   'String','Segment frames', ...
   'Style','checkbox', ...
   'Tag','SegmentFrameCheck');
cb_origin=cb_origin+[0 next_cb];
h1 = uicontrol('Parent',h0, ...
	'Units','pixels', ...
   'Callback','UpdateVizOrthoMode', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[cb_origin cb_size], ...
   'String','Referenced segment frames', ...
	'Style','checkbox', ...
	'Tag','ReferencedFrameCheck');
cb_origin=cb_origin+[0 next_cb];
h1 = uicontrol('Parent',h0, ...
	'Units','pixels', ...
   'Callback','UpdateVizOrthoMode', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[cb_origin cb_size], ...
   'String','Anatomical frames', ...
	'Style','checkbox', ...
	'Tag','AnatomicalFrameCheck');
cb_origin=cb_origin+[0 next_cb];
h1 = uicontrol('Parent',h0, ...
	'Units','pixels', ...
   'Callback','UpdateVizOrthoMode', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[cb_origin cb_size], ...
   'String','Anatomical markers', ...
	'Style','checkbox', ...
	'Tag','AnatomicalMarkerCheck');

cb_origin=cb_origin+[0 next_cb];
h1 = uicontrol('Parent',h0, ...
	'Units','pixels', ...
   'Callback','UpdateVizOrthoMode', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[cb_origin cb_size], ...
   'String','Stick figures', ...
	'Style','checkbox', ...
   'Tag','StickFigureCheck');

cb_origin=cb_origin+[0 next_cb];
h1 = uicontrol('Parent',h0, ...
	'Units','pixels', ...
   'Callback','UpdateVizOrthoMode', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
   'String','External Reaction Force', ...
	'Position',[cb_origin cb_size], ...
	'Style','checkbox', ...
	'Tag','GroundReactionForceCheck');

cb_size=[logo_size(1) cb_size(2)];
cb_origin=[separation fig_size(2)-2*separation-logo_size(2)-cb_size(2)];
h1 = uicontrol('Parent',h0, ...
	'Units','pixels', ...
   'Callback','UpdateVizOrthoMode', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
   'String','Bold lines', ...
	'Position',[cb_origin cb_size], ...
	'Style','checkbox', ...
   'Tag','BoldLineCheck');

cb_origin=cb_origin+[0 next_cb];
h1 = uicontrol('Parent',h0, ...
	'Units','pixels', ...
   'Callback','UpdateVizOrthoMode', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
   'String','Hold stick history', ...
	'Position',[cb_origin cb_size], ...
	'Style','checkbox', ...
   'Tag','KeepStickHistory');

eb_origin=slider_origin-[45 0];
eb_size=[40 slider_size(2)];
h1 = uicontrol('Parent',h0, ...
	'Units','pixels', ...
   'BackgroundColor',[1 1 1 ], ...
	'ListboxTop',0, ...
   'String','0', ...
	'Position',[eb_origin eb_size], ...
	'Style','edit', ...
	'Tag','TimeDisplay');

h1 = uicontrol('Parent',h0, ...
   'Style','Text',...
   'String','sec.',...
   'Position',[eb_origin-[0 20] eb_size],...
    'BackgroundColor',[0.8 0.8 0.8],...
   'FontSize',8);


zb_size=[40 20];
zb_origin=ca_origin+[ca_size(1) -zb_size(2)];
% Define the toggle button
zb = uicontrol('Parent',h0, ...
   'Units','pixels', ...
   'Callback','zoom', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'ListboxTop',0, ...
   'String','ZOOM', ...
   'Position',[zb_origin zb_size], ...
   'Style','togglebutton');

%  ==================================
%  MENU
%  ==================================

    % ################
    % ## menu TRIAL ##
    % ################

    h1 = uimenu('Parent',h0, ...
        'Label','&Trial', ...
        'Tag','BMCWM_Trial');
    h2 = uimenu('Parent',h1, ...
        'Callback','BodyMechMenuFcn(''load_trial_file'')', ...
        'Label','&Load Trial file (*.bmb)', ...
        'Tag','BMCWM_Trial_LoadTrialFile');
    h2 = uimenu('Parent',h1, ...
        'Callback','BodyMechMenuFcn(''clear_trial'')', ...
        'Label','&Clear Trial', ...
        'Tag','BMCWM_Trial_ClearTrial');
    h2 = uimenu('Parent',h1, ...
        'Callback','BodyMechMenuFcn(''update_trialheader'')', ...
        'Label','&Update TrialHeader', ...
        'Tag','BMCWM_Trial_UpdateTrialheader');

    h2 = uimenu('Parent',h1, ...
        'Label','Import &Marker file (OptoTrak)', ...
        'Separator','on', ...
        'Callback','BodyMechMenuFcn(''import_NDF'')', ...
        'Tag','BMCWM_Trial_ImportMarkerFile');
    h2 = uimenu('Parent',h1, ...
        'Callback','BodyMechMenuFcn(''import_C3D'')', ...
        'Enable','off', ...
        'Label','Import &C3D', ...
        'Tag','BMCWM_Trial_ImportC3D');
    h2 = uimenu('Parent',h1, ...
        'Label','Import &Analog file', ...
        'Tag','BMCWM_Trial_ImportAnalogFile');
    h3 = uimenu('Parent',h2 , ...
        'Callback','BodyMechMenuFcn(''import_MDF'')', ...
        'Label','Import &MDF', ...
        'Tag','BMCWM_Trial_ImportMDF');
    h3 = uimenu('Parent',h2 , ...
        'Enable','off', ...
        'Callback','BodyMechMenuFcn(''import_TMS'')', ...
        'Label','Import &TMS', ...
        'Tag','BMCWM_Trial_ImportTMS');
    h3 = uimenu('Parent',h2, ...
        'Enable','off', ...
        'Callback','BodyMechMenuFcn(''import_DAR'')', ...
        'Label','Import &DAR', ...
        'Tag','BMCWM_Trial_ImportDAR');

    h2 = uimenu('Parent',h1, ...
        'Callback','BodyMechMenuFcn(''kinematicscalculation'')', ...
        'Separator','on', ...
        'Label','&KinematicsCalculation', ...
        'Tag','BMCWM_Trial_Kinematicscalculation');
    h2 = uimenu('Parent',h1, ...
        'Label','KinematicsCalculation&Steps', ...
        'Tag','BMCWM_Trial_Kinematicscalculationsteps');
    
        h3 = uimenu('Parent',h2, ...
            'Callback','BodyMechMenuFcn(''selectmarkerkinematics'')', ...
            'Label','Select &TimeInterval Markers', ...
            'Tag','BMCWM_Trial_SelectMarkerKinematics');
        h3 = uimenu('Parent',h2, ...
            'Callback','BodyMechMenuFcn(''interpolatemarkers'')', ...
            'Label','&Interpolate Marker Kinematics', ...
            'Tag','BMCWM_Trial_InterpolateMarkers');
        h3 = uimenu('Parent',h2, ...
            'Callback','BodyMechMenuFcn(''calculate_clusterkinematics'')', ...
            'Label','Calculate &Cluster kinematics', ...
            'Tag','BMCWM_Trial_CalculateClusterKinematics');
        h3 = uimenu('Parent',h2, ...
            'Callback','BodyMechMenuFcn(''kinematics_posture_referenced'')', ...
            'Separator','on', ...
            'Label','Segment kinematics (&Posture referenced)', ...
            'Tag','BMCWM_Trial_KinematicsPostureReferenced');
        h3 = uimenu('Parent',h2, ...
            'Callback','BodyMechMenuFcn(''virtualmarks'')', ...
            'Label','&Virtual markers', ...
            'Tag','BMCWM_Trial_VirtualMarks');
        h3 = uimenu('Parent',h2, ...
            'Callback','BodyMechMenuFcn(''stickfigure'')', ...
            'Label','Create a default &Stick figure', ...
            'Tag','BMCWM_Trial_Stickfigure');
        h3 = uimenu('Parent',h2, ...
            'Enable','off', ...
            'Callback','BodyMechMenuFcn(''kinematics_anatomy_referenced'')', ...
            'Label','Segment kinematics (Anatomy referenced)', ...
            'Tag','BMCWM_Trial_KinematicsAnatomyReferenced');
        h3 = uimenu('Parent',h2, ...
            'Callback','BodyMechMenuFcn(''joint_kinematics_posture_ref'')', ...
            'Separator','on', ...
            'Label','&Joint kinematics (Posture referenced)', ...
            'Tag','BMCWM_Trial_JointKinematicsPosture');
        h3 = uimenu('Parent',h2, ...
            'Enable','off', ...
            'Callback','BodyMechMenuFcn(''joint_kinematics_anatomy_ref'')', ...
            'Label','&Joint kinematics (Anatomy referenced)', ...
            'Tag','BMCWM_Trial_JointKinematicsAnatomy');

    h2 = uimenu('Parent',h1, ...
        'Callback','BodyMechMenuFcn(''save_trialmodel'')', ...
        'Label','Save TrialModel (*.bmb)', ...
        'Separator','on', ...
        'Tag','BMCWM_Trial_SaveTrialmodel');
    h2 = uimenu('Parent',h1, ...
        'Enable','off', ...
        'Label','&Export data', ...
        'Tag','BMCWM_Trial_Exportdata');


if nargout > 0, fig = h0; end
%==========================================================
% END ### OrtoView ###
